/*
    modo: Representa o modo relacionado ao audio
    opcao: Opção do som, A B C ou P que é a opção padrão.
    arquivo: Trecho Relacionado
    atividade: Pagina da Atividade
    nivel: nivel da atividade
    corr: se é a correta
*/

export const modos_map = [
  { modo: "qual_e_o_par", texto: "Encontre o par!" },
  { modo: "rapido_devagar", texto: "Rápido ou Devagar!" },
  { modo: "grave_agudo", texto: "Grave ou Agudo!" },
];

export const nivel_ativ = [
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 1,
    texto: "Onde está a outra parte?",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 2,
    texto: "Onde está a outra parte?",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 3,
    texto: "Onde está a outra parte?",
  },

  { modo: "qual_e_o_par", nivel: 2, ativ: 1, texto: "Onde está o final?" },
  { modo: "qual_e_o_par", nivel: 2, ativ: 2, texto: "Onde está o final?" },
  { modo: "qual_e_o_par", nivel: 2, ativ: 3, texto: "Onde está o final?" },

  { modo: "qual_e_o_par", nivel: 3, ativ: 1, texto: "Onde está o início?" },
  { modo: "qual_e_o_par", nivel: 3, ativ: 2, texto: "Onde está o início?" },
  { modo: "qual_e_o_par", nivel: 3, ativ: 3, texto: "Onde está o início?" },

  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 1,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 2,
    texto: "Onde ela está mais devagar?",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 3,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 4,
    texto: "Onde ela está mais devagar?",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 5,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 6,
    texto: "Onde ela está mais devagar?",
  },

  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 1,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 2,
    texto: "Onde ela está mais devagar?",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 3,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 4,
    texto: "Onde ela está mais devagar?",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 5,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 6,
    texto: "Onde ela está mais devagar?",
  },

  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 1,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 2,
    texto: "Onde ela está mais devagar?",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 3,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 4,
    texto: "Onde ela está mais devagar?",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 5,
    texto: "Onde ela está mais rápida?",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 6,
    texto: "Onde ela está mais devagar?",
  },

  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 1,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 2,
    texto: "Onde ela está mais grave?",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 3,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 4,
    texto: "Onde ela está mais grave?",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 5,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 6,
    texto: "Onde ela está mais grave?",
  },

  {
    modo: "grave_agudo",
    nivel: 2,
    ativ: 1,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 2,
    ativ: 2,
    texto: "Onde ela está mais grave?",
  },
  {
    modo: "grave_agudo",
    nivel: 2,
    ativ: 3,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 2,
    ativ: 4,
    texto: "Onde ela está mais grave?",
  },
  {
    modo: "grave_agudo",
    nivel: 2,
    ativ: 5,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 2,
    ativ: 6,
    texto: "Onde ela está mais grave?",
  },

  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 1,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 2,
    texto: "Onde ela está mais grave?",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 3,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 4,
    texto: "Onde ela está mais grave?",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 5,
    texto: "Onde ela está mais aguda?",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 6,
    texto: "Onde ela está mais grave?",
  },
];

export const musicas_opcoes = [
  // Encontre o Par NÍVEL I Atividade 1
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 1,
    corr: 0,
    opcao: "A",
    arquivo: "CaiCaiBalao_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 1,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL I Atividade 2
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 2,
    corr: 0,
    opcao: "A",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 2,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 2,
    corr: 0,
    opcao: "C",
    arquivo: "CaiCaiBalao_Parte2_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL II Atividade 3
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "SitioMario_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "B",
    arquivo: "CaiCaiBalao_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 1,
    ativ: 3,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL II Atividade 1
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 1,
    corr: 0,
    opcao: "A",
    arquivo: "CaiCaiBalao_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 1,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL II Atividade 2
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 2,
    corr: 0,
    opcao: "A",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 2,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 2,
    corr: 0,
    opcao: "C",
    arquivo: "CaiCaiBalao_Parte2_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL II Atividade 3
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "SitioMario_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 3,
    corr: 0,
    opcao: "B",
    arquivo: "CaiCaiBalao_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 2,
    ativ: 3,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL III Atividade 1
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 1,
    corr: 1,
    opcao: "A",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 1,
    corr: 0,
    opcao: "B",
    arquivo: "Parabens_Parte1_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL III Atividade 2
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 2,
    corr: 0,
    opcao: "A",
    arquivo: "CaiCaiBalao_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 2,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 2,
    corr: 0,
    opcao: "C",
    arquivo: "SitioMario_Parte1_FaM_AndBase.wav",
  },

  // Encontre o Par NÍVEL III Atividade 3
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "Parabens_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "B",
    arquivo: "SitioMario_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 3,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Parte1_FaM_AndBase.wav",
  },
  {
    modo: "qual_e_o_par",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "D",
    arquivo: "CaiCaiBalao_Parte1_FaM_AndBase.wav",
  },

  // Rápido ou Devagar NÍVEL I Atividade 1
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 1,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_voztoc_DEVAGAR.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 1,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_voztoc_RAPIDO.wav",
  },

  // Rápido ou Devagar NÍVEL I Atividade 2
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 2,
    corr: 1,
    opcao: "A",
    arquivo: "Ciranda_voztoc_DEVAGAR.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 2,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_voztoc_RAPIDO.wav",
  },

  // Rápido ou Devagar NÍVEL I Atividade 3
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 3,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL I Atividade 4
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 4,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 4,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 4,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 4,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL I Atividade 5
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 5,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 5,
    corr: 1,
    opcao: "A",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 5,
    corr: 0,
    opcao: "B",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 5,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 5,
    corr: 0,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL I Atividade 6
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase_Grav.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 1,
    ativ: 6,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL II Atividade 1
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 1,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 1,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },

  // Rápido ou Devagar NÍVEL II Atividade 2
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 2,
    corr: 1,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 2,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },

  // Rápido ou Devagar NÍVEL II Atividade 3
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 3,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL II Atividade 4
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 4,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 4,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 4,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 4,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL II Atividade 5
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 5,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 5,
    corr: 1,
    opcao: "A",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 5,
    corr: 0,
    opcao: "B",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 5,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 5,
    corr: 0,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL II Atividade 6
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 6,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 6,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 6,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase_Grav.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 6,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 2,
    ativ: 6,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL I Atividade 1
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 1,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 1,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },

  // Rápido ou Devagar NÍVEL III Atividade 2
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 2,
    corr: 1,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 2,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },

  // Rápido ou Devagar NÍVEL III Atividade 3
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 3,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL III Atividade 4
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 4,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 4,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 4,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 4,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL III Atividade 5
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 5,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 5,
    corr: 1,
    opcao: "A",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 5,
    corr: 0,
    opcao: "B",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 5,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 5,
    corr: 0,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL III Atividade 6
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase_Grav.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 3,
    ativ: 6,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL IIII Atividade 1
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 1,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 1,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },

  // Rápido ou Devagar NÍVEL IIII Atividade 2
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 2,
    corr: 1,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 2,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },

  // Rápido ou Devagar NÍVEL IIII Atividade 3
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 3,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL IIII Atividade 4
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 4,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 4,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 4,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 4,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL IIII Atividade 5
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 5,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 5,
    corr: 1,
    opcao: "A",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 5,
    corr: 0,
    opcao: "B",
    arquivo: "ParabensVoce_Parte2_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 5,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 5,
    corr: 0,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },

  // Rápido ou Devagar NÍVEL IIII Atividade 6
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 6,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 6,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 6,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_FaM_AndBase_Grav.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 6,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_FaM_AndRap.wav",
  },
  {
    modo: "rapido_devagar",
    nivel: 4,
    ativ: 6,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Comp_FaM_AndDev.wav",
  },
  // Agudo ou Grave NÍVEL I Atividade 1
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_DoM_AndRap.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 1,
    corr: 1,
    opcao: "A",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 1,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },

  // Agudo ou Grave NÍVEL I Atividade 2
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_DoM_AndRap.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 2,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 2,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },

  // Agudo ou Grave NÍVEL I Atividade 3
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 3,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },

  // Agudo ou Grave NÍVEL I Atividade 4
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 4,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 4,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 4,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 4,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },

  // Agudo ou Grave NÍVEL I Atividade 5
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 5,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 5,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 5,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 5,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 5,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Comp_DoM_AndRap.wav",
  },

  // Agudo ou Grave NÍVEL I Atividade 6
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "B",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 6,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 1,
    ativ: 6,
    corr: 0,
    opcao: "D",
    arquivo: "Ciranda_Comp_SibM_AndDev.wav",
  },

  // Agudo ou Grave NÍVEL II Atividade 1
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 1,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 1,
    corr: 0,
    opcao: "A",
    arquivo: "CaiCai_Comp_DoM_AndRap.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 1,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },

  // Agudo ou Grave NÍVEL II Atividade 2
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 2,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_SibM_AndBaseAgu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 2,
    corr: 0,
    opcao: "A",
    arquivo: "CaiCai_Comp_SibM_AndDev.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 2,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_DoM_AndBase.wav",
  },

  // Agudo ou Grave NÍVEL II Atividade 3
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_DoM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 3,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 3,
    corr: 0,
    opcao: "C",
    arquivo: "Parabens_Comp_DoM_AndBase.wav",
  },

  // Agudo ou Grave NÍVEL II Atividade 4
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 4,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 4,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 4,
    corr: 1,
    opcao: "B",
    arquivo: "Ciranda_Comp_DoM_AndBase_Grav.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 4,
    corr: 0,
    opcao: "C",
    arquivo: "SitioVelhoMario_Comp_DoM_AndBase.wav",
  },

  // Agudo ou Grave NÍVEL II Atividade 5
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 5,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_DoM_AndBaseGrav.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 5,
    corr: 0,
    opcao: "A",
    arquivo: "Parabens_Comp_DoM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 5,
    corr: 0,
    opcao: "B",
    arquivo: "Parabens_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 5,
    corr: 1,
    opcao: "C",
    arquivo: "Ciranda_Comp_SibM_AndBase_Agu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 5,
    corr: 0,
    opcao: "D",
    arquivo: "Ciranda_Comp_DoM_AndRap.wav",
  },

  // Agudo ou Grave NÍVEL II Atividade 6
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "P",
    arquivo: "Ciranda_Comp_SibM_AndBaseAgu.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "A",
    arquivo: "Ciranda_Comp_SibM_AndDev.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "B",
    arquivo: "CaiCai_Comp_FaM_AndBase.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 6,
    corr: 0,
    opcao: "C",
    arquivo: "Ciranda_Comp_SibM_AndRap.wav",
  },
  {
    modo: "grave_agudo",
    nivel: 3,
    ativ: 6,
    corr: 1,
    opcao: "D",
    arquivo: "Ciranda_Comp_DoM_AndBase.wav",
  },
];
